# this pulls in the dictionary generated by simple_crawler_modified.py
# and returns a doubly-linked ring of tnodes, one tnode for each unique url
# with pointer to starting url and fields for each tnode set to the default values

from fibheap import *
from simple_crawler import *

# just assume for now that you will be passed a dict
# returns a fibheap
